# Generated by Django 2.1.5 on 2019-02-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
