# Generated by Django 2.1.5 on 2019-03-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20190301_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('details', models.TextField()),
                ('dated', models.DateField()),
            ],
        ),
    ]
