# Generated by Django 2.1.5 on 2019-03-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_patientdtl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientDtl',
            new_name='PatientD',
        ),
    ]
