# Generated by Django 2.1.5 on 2019-03-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20190307_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientd',
            options={'ordering': ['-dated']},
        ),
        migrations.AlterField(
            model_name='patientd',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
